version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/models:/app/models
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80" # Map host port 4200 to container port 80 (Nginx)
    depends_on:
      - backend 